apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:  # control how much capacity can be used by the pods
    storage: 1Gi 
  volumeMode: Filesystem # we have a folder inside the virtual machine
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /data
    type: DirectoryOrCreate
 